server:
  port: 4923

logging:
  pattern:
    level: "%5p %X{CorrelationId}"
  level:
    root: warn
    org.elasticsearch.client: error
    com.k_int.rosetta: info
    com.k_int.rosetta.web.api.iiif: debug
    com.k_int.rosetta.web.iiif.presentation.v3: debug
    com.k_int.rosetta.provider.elastic: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - health

springdoc:
  api-docs:
    path: /api/v1/spec

rosetta:
  cache:
    enabled: false
    use_cache_service: false
  profile:
    profiles:
      - name: default
        glyphs:
          policy: list
          names:
            - api-default
  transform:
    enabled: true
    timeout_millis: 6000
    glyphs:
      - name: api-default
        type: proteus
        properties:
          mutable: true
          file: ./config/jpt.json
          input: source
          output: detail
  provider:
    providers:
      - name: elasticsearch
        type: elasticsearch
        domainConverter: es-converter
        properties:
          host: ciim-public-es-http.etna
          port: 9200
          index: ciim
          username: elastic
          password: 6tVhH4oGK23TU895Pfa04B8K
          search_config:
            search_fields:
              - field: "description.value"
                boost: 2
              - field: "summary.title"
                boost: 5
              - field: "title.value"
                boost: 4
              - field: "name.value"
                boost: 3
              - field: "summary.title.value"
                boost: 5
          date_range_format: "{from} - {to}"
          date_aggregations:
            - path: "origination.date.from"
              agg_name: "coveringDates"
              additional_path: "origination.date.to"
              format: "yyyy"
              date_ranges:
                - from: "1100"
                  to: "1199"
                - from: "1200"
                  to: "1299"
                - from: "1300"
                  to: "1399"
                - from: "1400"
                  to: "1499"
                - from: "1500"
                  to: "1599"
                - from: "1600"
                  to: "1699"
                - from: "1700"
                  to: "1799"
                - from: "1800"
                  to: "1899"
                - from: "1900"
                  to: "1924"
                - from: "1925"
                  to: "1949"
                - from: "1950"
                  to: "3000"
            - path: "availability.access.opening.date.from"
              agg_name: "openingFromDate"
            - path: "availability.access.opening.date.to"
              agg_name: "openingToDate"
            - path: "origination.date.from"
              agg_name: "coveringFromDate"
            - path: "origination.date.to"
              agg_name: "coveringToDate"
          path_config:
            paths:
              topic: "topic.summary.title.keyword"
              collection: "collection.identifier.value"
              group: "@datatype.group.value"
              level: "level.value"
              type: "repository.@datatype.actual"
              country: "place.@hierarchy.name.value.keyword"
              closure: "availability.closure.label.value.keyword"
              catalogueSource: "source.value"
              heldBy: "repository.name.value.keyword"
              webReference: "web.identifier.value.lower"

  domain:
    converters:
      - name: es-converter
        type: elastic-default

  plugins:
    iiif:
      baseUrl: http://localhost/
      externalMediaBaseUrl: http://localhost/mediaLib/
      IIIFMediaBaseUrl: http://localhost:8182/iiif/3/
      mediaArtifact: mid
      identifierQueryString: identifier.value
      manifestKey:
        keyType: IDENTIFIER
        identifierType: accession number