bases:
  - ../../ohos/base
  - ../../ohos/eks
  - ../../ohos/kong
  - ../../ohos/ingress-ciim
  - ../../ohos/ciim
  - ../../ohos/internal-es
  - ../../ohos/public-es
  - ../../ohos/ciim-ui
  - ../../ohos/public-clean-es
  - ../../ohos/rosetta-3
  - ../../ohos/rosetta-3-graphql
commonAnnotations:
  environment: dev