bases:
  - ../../base
  - ../../eks
  - ../../unmanaged-public-es
  - ../../ohos/base
  - ../../ohos/eks
  - ../../ohos/kong
  - ../../ohos/ingress
  - ../../ohos/ciim
  - ../../ohos/mysql
  - ../../ohos/internal-es
  - ../../ohos/public-es
  - ../../ohos/ciim-ui
  - ../../ohos/public-clean-es
  - ../../ohos/rosetta-3
  - ../../ohos/rosetta-3-graphql
  - ../../ohos/acme
  - ../../internal-es
  - ../../public-es
  - ../../ingress
  - ../../rosetta-3
  - ../../api
  - ../../acme
  - ../../rosetta-3-TEST
commonAnnotations:
  environment: dev
patchesStrategicMerge:
  - database-tagged.yml
  - public-es-tagged.yml