bases:
  - ../../base
  - ../../eks
  - ../../unmanaged-public-es
  - ../../ohos/base
  - ../../ohos/eks
  - ../../ohos/kong
  - ../../ohos/ingress
  - ../../ohos/ciim
  - ../../ohos/mysql
  - ../../ohos/internal-es
  - ../../ohos/public-es
  - ../../ohos/ciim-ui
  - ../../ohos/public-clean-es
  - ../../public-es
commonAnnotations:
  environment: dev
patchesStrategicMerge:
  - public-es-tagged.yml