bases:
  - ../../base
  - ../../storage
  - ../../internal-es
  - ../../public-es
  - ../../ciim-staging
  - ../../ciim-ingress
  - ../../rosetta-3-ciim
  - ../../acme
  - ../../public-es-2
  - ../../rosetta-3-ciim-staging
  - ../../rosetta-3-ciim-prod
commonAnnotations:
  environment: dev
patchesStrategicMerge:
  - ciim-tagged.yml
  - database-tagged.yml