apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosetta-tna
  namespace: etna
spec:
  selector:
    matchLabels:
      app: rosetta-tna
  revisionHistoryLimit: 5
  replicas: 1
  progressDeadlineSeconds: 600
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rosetta-tna
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: rosetta-config
          configMap:
            name: rosetta-config
      initContainers:
        - name: set-rosetta-permissions
          image: registry.hub.docker.com/library/busybox:latest
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', 'chmod -R 777 /rosetta' ]
      containers:
        - name: rosetta
          image: public.ecr.aws/v3w7q3a1/rosetta:tna
          imagePullPolicy: Always
          ports:
            - name: rosetta-port
              containerPort: 4923
              protocol: TCP
          volumeMounts:
            - name: ciim-config
              mountPath: /rosetta/config
          env:
            - name: JAVA_OPTS
              value: "-Dspring.profiles.active=non-default-for-trace-logging -XX:MaxRAMPercentage=80.0 -XX:+PrintFlagsFinal -XX:+UseZGC"
          resources:
            requests:
              memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rosetta-service
  namespace: etna
spec:
  type: ClusterIP
  selector:
    app: rosetta-tna
  ports:
    - protocol: TCP
      port: 4923
      targetPort: 4923
      name: rosetta-port