apiVersion: v1
kind: Secret
metadata:
  name: ciim-mysql-creds
  namespace: tna-ohos
type: Opaque
data:
  ciim.db.password: dzVDeEZpOXIxZlR1T3BSMHpXQXY=
  ciim.db.username: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: internal-es-pass
  namespace: tna-ohos
type: Opaque
data:
  elasticsearch.auth.password: U1RoRWFFcGlUMjg0Wm1Jd05ra3lSamxwTkRZM2NqaFk=
---
apiVersion: v1
kind: Secret
metadata:
  name: public-es-pass
  namespace: tna-ohos
type: Opaque
data:
  publication.es.auth.password: UkRGd1pETnZOakJaZW1OcE1rczBOelV4T0U5VmRGVm8=
---
apiVersion: v1
kind: Secret
metadata:
  name: public-es-clean-pass
  namespace: tna-ohos
type: Opaque
data:
  publication.es.clean.auth.password: VWxKUFR6WTBkV1UxYmxwaU16a3dZamN3U0c1Vk1rVTA=
---
apiVersion: v1
kind: Secret
metadata:
  name: ciim-encryption-key
  namespace: tna-ohos
type: Opaque
data:
  ciim.encryption_key: YzFCTGMxSnhOMjVLWmxKR01sSktkV2RJU0hoaFIwVT0=